[build]
target = "rpi3.json"

[target.aarch64-unknown-none]
linker = "/usr/local/opt/llvm/bin/ld.lld"


[target.'cfg(all())']
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "link-arg=--strip-all"
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]